#!/usr/bin/env bash
# Regenerates pokedex.tsv, the local dex-number/typing table logo.sh reads.
#
# Two sources are joined:
#   * pokeget's own embedded "Display Name,slug" table, read straight out of
#     the binary. Its order IS the national dex, so the line number is the dex
#     number -- and reading it from the installed binary means the table always
#     matches the sprites pokeget can actually draw.
#   * PokeAPI's CSV export, for typings.
#
# Run it manually to refresh, or let logo.sh fire it in the background the
# first time it meets a Pokemon that isn't in the table (a pokeget update
# adding a new generation, typically).
#
# The result is written to a temp file and moved into place only on success,
# so a failed or offline run leaves the existing table untouched.

set -uo pipefail

readonly SELF_DIR=${BASH_SOURCE[0]%/*}
readonly OUT="$SELF_DIR/pokedex.tsv"
readonly CSV_BASE="https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv"
readonly LOG="${XDG_STATE_HOME:-$HOME/.local/state}/fastfetch-pokedex.log"

log() {
  mkdir -p "${LOG%/*}" 2>/dev/null
  printf '%s %s\n' "$(date -Is)" "$*" >>"$LOG" 2>/dev/null
}

die() {
  log "FAILED: $*"
  exit 1
}

command -v curl >/dev/null 2>&1 || die "curl not found"
command -v strings >/dev/null 2>&1 || die "strings not found (install binutils)"

pokeget=$(command -v pokeget) || die "pokeget not found"

tmp=$(mktemp -d) || die "could not create temp dir"
trap 'rm -rf "$tmp"' EXIT

# --- 1. dex order, from the pokeget binary ---------------------------------
# The embedded table is a run of "Name,slug" lines. Take everything from
# Bulbasaur (dex 1) and stop at the first line that is not well formed, which
# is where the table ends and other binary data begins.
strings -n 4 "$pokeget" 2>/dev/null \
  | sed -n '/Bulbasaur,bulbasaur/,$p' \
  | sed '1s/^.*Bulbasaur,bulbasaur/Bulbasaur,bulbasaur/' \
  | awk -F, '
      NF == 2 && $1 ~ /^[^,]+$/ && $2 ~ /^[a-z0-9'"'"'-]+$/ { print; next }
      { exit }
    ' >"$tmp/dex.csv"

dex_count=$(wc -l <"$tmp/dex.csv")
(( dex_count > 100 )) || die "only $dex_count names extracted from pokeget; layout may have changed"

# --- 2. typings, from PokeAPI ----------------------------------------------
for f in types.csv pokemon_types.csv; do
  curl -fsSL --max-time 45 "$CSV_BASE/$f" -o "$tmp/$f" || die "could not fetch $f"
  [[ -s $tmp/$f ]] || die "$f came back empty"
done

# --- 3. join ----------------------------------------------------------------
# One pass, files given in order: type_id -> type name, then dex -> slot
# ordered typings, then walk the dex list and emit. Row count goes to stderr
# so the caller can sanity check it before installing.
awk -F, -v dexfile="$tmp/dex.csv" '
  FNR == 1 && FILENAME ~ /\/types\.csv$/ { next }
  FILENAME ~ /\/types\.csv$/ { tname[$1] = $2; next }

  FNR == 1 && FILENAME ~ /pokemon_types\.csv$/ { next }
  FILENAME ~ /pokemon_types\.csv$/ {
    id = $1 + 0
    if (id > 10000) next
    if ($3 + 0 == 1) first[id] = tname[$2]
    else if ($3 + 0 == 2) second[id] = tname[$2]
    next
  }

  END {
    printf "# slug\tdex\tname\ttypes   (generated by update-pokedex.sh; local, no runtime network)\n"
    n = 0
    while ((getline line < dexfile) > 0) {
      n++
      split(line, p, ",")
      name = p[1]; slug = p[2]
      t = first[n]
      if (t == "") continue                          # no typing known, skip
      if (second[n] != "") t = t "," second[n]
      printf "%s\t%d\t%s\t%s\n", slug, n, name, t
      written++
    }
    printf "%d\n", written > "/dev/stderr"
  }
' "$tmp/types.csv" "$tmp/pokemon_types.csv" >"$tmp/pokedex.tsv" 2>"$tmp/count"

written=$(cat "$tmp/count" 2>/dev/null)
[[ ${written:-0} -gt 100 ]] || die "join produced only ${written:-0} rows"

# --- 4. install atomically --------------------------------------------------
old_count=0
[[ -f $OUT ]] && old_count=$(grep -vc '^#' "$OUT" 2>/dev/null)

mv "$tmp/pokedex.tsv" "$OUT" || die "could not write $OUT"
log "OK: $written entries (was $old_count) from $dex_count pokeget names"

exit 0
