# --- Navigation & listing ---
alias ll="lsd -la"
alias la="lsd -a"
alias l="lsd"
alias c="clear"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias mkcd="mkdir -p $1 && cd $1"
alias home="cd ~"
alias desk="cd ~/Desktop"
alias docs="cd ~/Documents"
alias dls="cd ~/Downloads"
alias pics="cd ~/Pictures"
alias vids="cd ~/Videos"
alias music="cd ~/Music"
alias repos="cd /mtn/Data/Repos"
alias root="cd /"

# --- Git & VCS ---
alias gs="git status"
alias gp="git pull"
alias gc="git commit"
alias gca="git commit -a"
alias gco="git checkout"
alias gb="git branch"
alias gd="git diff"
alias gcm="git commit -m"
alias lzgit="lazygit"

# --- Build & Dev tools ---
alias make="make -j$(nproc)"
alias ninja="ninja -j$(nproc)"
alias n="ninja"

# --- Python / Dev env ---
alias ipy="ipython"
alias py="python"
alias mkvenv="python -m venv .venv && source .venv/bin/activate"
alias venv="source .venv/bin/activate"
alias pipup="pip install --upgrade pip setuptools wheel"
alias pipreqs="pipreqs --force ."
alias djrun="python manage.py runserver"
alias djmigrate="python manage.py migrate"
alias djcreatesuperuser="python manage.py createsuperuser"

# --- Shell / zsh helpers ---
alias reloadzsh="source ~/.zshrc"
alias zshreload="source ~/.zshrc"
alias zshconfig="code ~/.zshrc ~/.zsh/ ~/.zshenv ~/.zlogin"
alias precompile="sh $HOME/.zsh/bin/precompile_zsh.sh"
alias p10kconfig="p10k configure"
alias dnf="sudo dnf"
alias update="sudo dnf update && flatpak update && brew update && brew upgrade"
alias install="sudo dnf install"
alias remove="sudo dnf remove"
alias imgcat="wezterm imgcat"
alias clr="clear && fastfetch"
alias rsync='rsync -zavhP --delete'

# --- Utilities / misc ---
alias ports="sudo lsof -i -P -n | grep LISTEN"
alias jctl="journalctl -p 3 -xb"
alias rip="expac --timefmt='%Y-%m-%d %T' '%l	%n %v' | sort | tail -200 | nl"
alias path='printf "%s\n" ${(s/:/)PATH}'
alias please="sudo"
alias no="nano"
alias ani="anipy-cli"
alias calc="bc -l"
alias matrix="unimatrix -n -f -i -a -s 96 -l o"
alias cmatrix="unimatrix -n -f -i -a -s 96 -l o"

# --- Search / text tools ---
alias grep="rg"
alias fgrep="rg -F"
alias egrep="rg -E"
alias search="rg"
alias findtext="rg"
alias ffind="fd"

# --- Monitoring / interactive ---
alias bt="btop"
alias ht="htop"
alias watch="gotop --watch"

# --- Media / images ---
alias imgview="sxiv"
alias imgconvert="magick"
alias pdfmerge="pdfunite"
alias pdfsplit="pdfseparate"
alias pdfcompress="ps2pdf"
alias vidconvert="ffmpeg -i"
alias vidcompress="ffmpeg -i $1 -vcodec libx265 -crf 28 $2"
alias audconvert="ffmpeg -i"
alias audcompress="ffmpeg -i $1 -b:a 128k $2"
alias audextract="ffmpeg -i $1 -q:a 0 -map a $2"
alias gifsicle="gifsicle --optimize=3 --colors 256"
alias gifview="gifview"
alias gifconvert="gifsicle -O3"
alias gifcompress="gifsicle -O3 --colors 128"
alias mpvplay="mpv"
alias vlcplay="vlc"
alias ytplay="yt-dlp -o - | mpv --no-cache -"
alias ytdownload="yt-dlp"
alias ytaudio="yt-dlp -x --audio-format mp3"
alias ytvideo="yt-dlp -f bestvideo+bestaudio"
alias imgresize="magick convert $1 -resize $2 $3"
alias imgcompress="magick convert $1 -quality $2 $3"
alias imgoptimize="oxipng -o7 $1"

# --- Networking / web ---
alias wget="wget --show-progress --progress=bar:force:noscroll"
alias curl="curl -#"
alias myip="curl ifconfig.me"
alias ping="ping -c 5"
alias ports="sudo lsof -i -P -n | grep LISTEN"
alias netstat="ss -tuln"
alias traceroute="traceroute -m 30"
alias httpserver="python -m http.server 8000"
alias ftpserver="python -m pyftpdlib -p 21 -w"
alias speedtest="speedtest-cli"
alias dnslookup="dig +short"
alias nslookup="nslookup"
alias whois="whois"
alias ipinfo="curl ipinfo.io"
alias sshcopy="ssh-copy-id"
alias sshkeygen="ssh-keygen -t ed25519 -C"
alias proxychains="proxychains4"
alias torstart="sudo systemctl start tor.service"
alias torstop="sudo systemctl stop tor.service"
alias torstatus="systemctl status tor.service"
